version: '3.8'

services:
  gd-nginx:
    container_name: gd-nginx
    build:
      context: ../
    image: nginx:stable-alpine
    ports:
      - ${WEBSERVER_PORT}:80
    env_file: .env
    volumes:
      - ../game:/var/www/game
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/logs:/var/log/nginx/

  gd-client:
    container_name: gd-client
    build:
      context: ../
      dockerfile: ./docker/node/Dockerfile
    env_file: .env
    volumes:
      - ./client:/var/www/client